38/hoc types
graasp/graasp-apps-query-client pull request #39
Opened 2022-06-14 15:56 UTC by spaenleh

This PR adds corresponding types to the HOC (`withToken` and `withContext`) such that they correspond to the hooks they use. 

### Changes:
- The context (`LocalContext`) changed from a `Map` to a `Record` (type is `RecordOf<LocalContext>`) through the use of the `LocalContextRecord` factory.
- `Context` enum is renamed to `CONTEXTS` in order to not conflict with the LocalContext's `Context` export in `index.ts`

### Fixes: 
- MirageJS dates are now in ISO format 

closes #38

2022-06-15 13:18 UTC, pyphilia requested changes
Thanks for the types 🏗️  Let me know when you're done with what we discussed (use Contexts from graasp-utils)

2022-06-15 13:18 UTC, pyphilia commented on src/mockServer/mockServer.ts
> +  console.log('Mock server created, with appContext:', appContext);
Remove console.

2022-06-15 16:14 UTC, spaenleh commented
This PR now uses React18 and react-query v4 in beta. And we now use `microbundle` instead of `microbundle-crl`.

2022-06-16 12:03 UTC, pyphilia approved these changes
👏

2022-06-30 12:11 UTC, merged